import Foundation

enum Language: String, CaseIterable, Identifiable {
    case english    = "English"
    case russian    = "Русский"
    case german     = "Deutsch"
    case french     = "Français"
    case spanish    = "Español"
    case italian    = "Italiano"
    case portuguese = "Português"
    case polish     = "Polski"
    case chinese    = "中文"
    case japanese   = "日本語"
    case hindi      = "हिन्दी"

    var id: String { rawValue }
}

extension Notification.Name {
    static let languageChanged = Notification.Name("languageChanged")
}

/// Returns the translation of `key` in the current app language.
/// Falls back to the key itself (English) if no translation is found.
func t(_ key: String) -> String {
    let lang = AppSettings.shared.language
    guard lang != .english else { return key }
    return translations[lang]?[key] ?? key
}

/// Like `t()` but with printf-style format arguments.
func tf(_ key: String, _ args: CVarArg...) -> String {
    String(format: t(key), arguments: args)
}

// MARK: - Translations

private let translations: [Language: [String: String]] = [

    // MARK: Russian
    .russian: [
        "Settings...": "Настройки...",
        "Quit": "Выйти",
        "Language": "Язык",
        "Modifier Key": "Клавиша-модификатор",
        "Window Sizes": "Размеры окон",
        "Preview": "Предпросмотр",
        "Permissions": "Разрешения",
        "Window Switcher": "Переключатель окон",
        "Window Control": "Управление окнами",
        "Move to Desktop": "Переместить на рабочий стол",
        "Hotkeys": "Горячие клавиши",
        "Left width:": "Ширина левой:",
        "Left: %d%% / Right: %d%%": "Лево: %d%% / Право: %d%%",
        "Top height:": "Высота верхней:",
        "Top: %d%% / Bottom: %d%%": "Верх: %d%% / Низ: %d%%",
        "Accessibility": "Специальные возможности",
        "Grant": "Разрешить",
        "OK": "OK",
        "Refresh Status": "Обновить статус",
        "Launch at Login": "Запуск при входе",
        "Enable %@ + Tab window switcher": "Включить %@ + Tab переключатель",
        "Experimental feature. Works best within a single Space — switching to windows on other Spaces may be unreliable.": "Экспериментальная функция. Лучше работает в одном Space — переключение на другие Space может быть нестабильным.",
        "Enable window control hotkeys": "Включить горячие клавиши управления",
        "Maximize / Restore": "Развернуть / Восстановить",
        "Minimize all windows": "Свернуть все окна",
        "Minimize active window": "Свернуть активное окно",
        "Close active window": "Закрыть активное окно",
        "Center window": "Центрировать окно",
        "Enable %@ + 1–9 to move window": "Включить %@ + 1–9 для перемещения",
        "Text Switcher": "Переключатель раскладки",
        "Enable double Shift to switch layout": "Двойной Shift для смены раскладки",
        "Switch windows (experimental)": "Переключение окон (эксп.)",
        "Center (%d%%)": "По центру (%d%%)",
        "Move window to Desktop N": "Переместить на рабочий стол N",
        "Left half": "Левая половина",
        "Right half": "Правая половина",
        "Top half": "Верхняя половина",
        "Bottom half": "Нижняя половина",
        "Top left quarter": "Верхний левый квадрант",
        "Bottom left quarter": "Нижний левый квадрант",
        "Top right quarter": "Верхний правый квадрант",
        "Bottom right quarter": "Нижний правый квадрант",
        "Top left eighth": "Верхняя левая восьмая",
        "Bottom left eighth": "Нижняя левая восьмая",
        "Top right eighth": "Верхняя правая восьмая",
        "Bottom right eighth": "Нижняя правая восьмая",
    ],

    // MARK: German
    .german: [
        "Settings...": "Einstellungen...",
        "Quit": "Beenden",
        "Language": "Sprache",
        "Modifier Key": "Modifikatortaste",
        "Window Sizes": "Fenstergrößen",
        "Preview": "Vorschau",
        "Permissions": "Berechtigungen",
        "Window Switcher": "Fensterwechsler",
        "Window Control": "Fensterverwaltung",
        "Move to Desktop": "Zu Desktop verschieben",
        "Hotkeys": "Tastenkürzel",
        "Left width:": "Linke Breite:",
        "Left: %d%% / Right: %d%%": "Links: %d%% / Rechts: %d%%",
        "Top height:": "Obere Höhe:",
        "Top: %d%% / Bottom: %d%%": "Oben: %d%% / Unten: %d%%",
        "Accessibility": "Bedienungshilfen",
        "Grant": "Erlauben",
        "OK": "OK",
        "Refresh Status": "Status aktualisieren",
        "Launch at Login": "Bei Anmeldung starten",
        "Enable %@ + Tab window switcher": "%@ + Tab Fensterwechsler aktivieren",
        "Experimental feature. Works best within a single Space — switching to windows on other Spaces may be unreliable.": "Experimentelle Funktion. Funktioniert am besten in einem Space — das Wechseln zu Fenstern in anderen Spaces kann unzuverlässig sein.",
        "Enable window control hotkeys": "Fensterverwaltungs-Tastenkürzel aktivieren",
        "Maximize / Restore": "Maximieren / Wiederherstellen",
        "Minimize all windows": "Alle Fenster minimieren",
        "Minimize active window": "Aktives Fenster minimieren",
        "Close active window": "Aktives Fenster schließen",
        "Center window": "Fenster zentrieren",
        "Enable %@ + 1–9 to move window": "%@ + 1–9 zum Verschieben aktivieren",
        "Switch windows (experimental)": "Fenster wechseln (experimentell)",
        "Center (%d%%)": "Zentrieren (%d%%)",
        "Move window to Desktop N": "Fenster zu Desktop N verschieben",
        "Left half": "Linke Hälfte",
        "Right half": "Rechte Hälfte",
        "Top half": "Obere Hälfte",
        "Bottom half": "Untere Hälfte",
        "Top left quarter": "Obere linke Ecke",
        "Bottom left quarter": "Untere linke Ecke",
        "Top right quarter": "Obere rechte Ecke",
        "Bottom right quarter": "Untere rechte Ecke",
        "Top left eighth": "Oberes linkes Achtel",
        "Bottom left eighth": "Unteres linkes Achtel",
        "Top right eighth": "Oberes rechtes Achtel",
        "Bottom right eighth": "Unteres rechtes Achtel",
    ],

    // MARK: French
    .french: [
        "Settings...": "Paramètres...",
        "Quit": "Quitter",
        "Language": "Langue",
        "Modifier Key": "Touche modificatrice",
        "Window Sizes": "Tailles des fenêtres",
        "Preview": "Aperçu",
        "Permissions": "Autorisations",
        "Window Switcher": "Sélecteur de fenêtres",
        "Window Control": "Contrôle des fenêtres",
        "Move to Desktop": "Déplacer vers le bureau",
        "Hotkeys": "Raccourcis clavier",
        "Left width:": "Largeur gauche :",
        "Left: %d%% / Right: %d%%": "Gauche : %d%% / Droite : %d%%",
        "Top height:": "Hauteur haut :",
        "Top: %d%% / Bottom: %d%%": "Haut : %d%% / Bas : %d%%",
        "Accessibility": "Accessibilité",
        "Grant": "Autoriser",
        "OK": "OK",
        "Refresh Status": "Actualiser l'état",
        "Launch at Login": "Lancer à la connexion",
        "Enable %@ + Tab window switcher": "Activer le sélecteur %@ + Tab",
        "Experimental feature. Works best within a single Space — switching to windows on other Spaces may be unreliable.": "Fonctionnalité expérimentale. Fonctionne mieux dans un seul Space — le passage aux autres Spaces peut être instable.",
        "Enable window control hotkeys": "Activer les raccourcis de contrôle",
        "Maximize / Restore": "Agrandir / Restaurer",
        "Minimize all windows": "Réduire toutes les fenêtres",
        "Minimize active window": "Réduire la fenêtre active",
        "Close active window": "Fermer la fenêtre active",
        "Center window": "Centrer la fenêtre",
        "Enable %@ + 1–9 to move window": "Activer %@ + 1–9 pour déplacer",
        "Switch windows (experimental)": "Changer de fenêtre (expérimental)",
        "Center (%d%%)": "Centrer (%d%%)",
        "Move window to Desktop N": "Déplacer la fenêtre vers le bureau N",
        "Left half": "Moitié gauche",
        "Right half": "Moitié droite",
        "Top half": "Moitié supérieure",
        "Bottom half": "Moitié inférieure",
        "Top left quarter": "Quart supérieur gauche",
        "Bottom left quarter": "Quart inférieur gauche",
        "Top right quarter": "Quart supérieur droit",
        "Bottom right quarter": "Quart inférieur droit",
        "Top left eighth": "Huitième supérieur gauche",
        "Bottom left eighth": "Huitième inférieur gauche",
        "Top right eighth": "Huitième supérieur droit",
        "Bottom right eighth": "Huitième inférieur droit",
    ],

    // MARK: Spanish
    .spanish: [
        "Settings...": "Ajustes...",
        "Quit": "Salir",
        "Language": "Idioma",
        "Modifier Key": "Tecla modificadora",
        "Window Sizes": "Tamaños de ventana",
        "Preview": "Vista previa",
        "Permissions": "Permisos",
        "Window Switcher": "Selector de ventanas",
        "Window Control": "Control de ventanas",
        "Move to Desktop": "Mover al escritorio",
        "Hotkeys": "Atajos de teclado",
        "Left width:": "Ancho izquierdo:",
        "Left: %d%% / Right: %d%%": "Izquierda: %d%% / Derecha: %d%%",
        "Top height:": "Altura superior:",
        "Top: %d%% / Bottom: %d%%": "Arriba: %d%% / Abajo: %d%%",
        "Accessibility": "Accesibilidad",
        "Grant": "Permitir",
        "OK": "OK",
        "Refresh Status": "Actualizar estado",
        "Launch at Login": "Iniciar al acceder",
        "Enable %@ + Tab window switcher": "Activar selector %@ + Tab",
        "Experimental feature. Works best within a single Space — switching to windows on other Spaces may be unreliable.": "Función experimental. Funciona mejor en un solo Space — cambiar a otros Spaces puede ser inestable.",
        "Enable window control hotkeys": "Activar atajos de control",
        "Maximize / Restore": "Maximizar / Restaurar",
        "Minimize all windows": "Minimizar todas las ventanas",
        "Minimize active window": "Minimizar ventana activa",
        "Close active window": "Cerrar ventana activa",
        "Center window": "Centrar ventana",
        "Enable %@ + 1–9 to move window": "Activar %@ + 1–9 para mover",
        "Switch windows (experimental)": "Cambiar ventanas (experimental)",
        "Center (%d%%)": "Centrar (%d%%)",
        "Move window to Desktop N": "Mover ventana al escritorio N",
        "Left half": "Mitad izquierda",
        "Right half": "Mitad derecha",
        "Top half": "Mitad superior",
        "Bottom half": "Mitad inferior",
        "Top left quarter": "Cuarto superior izquierdo",
        "Bottom left quarter": "Cuarto inferior izquierdo",
        "Top right quarter": "Cuarto superior derecho",
        "Bottom right quarter": "Cuarto inferior derecho",
        "Top left eighth": "Octavo superior izquierdo",
        "Bottom left eighth": "Octavo inferior izquierdo",
        "Top right eighth": "Octavo superior derecho",
        "Bottom right eighth": "Octavo inferior derecho",
    ],

    // MARK: Italian
    .italian: [
        "Settings...": "Impostazioni...",
        "Quit": "Esci",
        "Language": "Lingua",
        "Modifier Key": "Tasto modificatore",
        "Window Sizes": "Dimensioni finestra",
        "Preview": "Anteprima",
        "Permissions": "Autorizzazioni",
        "Window Switcher": "Selettore finestre",
        "Window Control": "Controllo finestre",
        "Move to Desktop": "Sposta sul desktop",
        "Hotkeys": "Scorciatoie",
        "Left width:": "Larghezza sinistra:",
        "Left: %d%% / Right: %d%%": "Sinistra: %d%% / Destra: %d%%",
        "Top height:": "Altezza superiore:",
        "Top: %d%% / Bottom: %d%%": "Alto: %d%% / Basso: %d%%",
        "Accessibility": "Accessibilità",
        "Grant": "Consenti",
        "OK": "OK",
        "Refresh Status": "Aggiorna stato",
        "Launch at Login": "Avvia all'accesso",
        "Enable %@ + Tab window switcher": "Attiva selettore %@ + Tab",
        "Experimental feature. Works best within a single Space — switching to windows on other Spaces may be unreliable.": "Funzione sperimentale. Funziona meglio in un singolo Space — il passaggio ad altri Space può essere inaffidabile.",
        "Enable window control hotkeys": "Abilita scorciatoie controllo finestre",
        "Maximize / Restore": "Ingrandisci / Ripristina",
        "Minimize all windows": "Minimizza tutte le finestre",
        "Minimize active window": "Minimizza finestra attiva",
        "Close active window": "Chiudi finestra attiva",
        "Center window": "Centra finestra",
        "Enable %@ + 1–9 to move window": "Attiva %@ + 1–9 per spostare",
        "Switch windows (experimental)": "Cambia finestra (sperimentale)",
        "Center (%d%%)": "Centra (%d%%)",
        "Move window to Desktop N": "Sposta finestra al desktop N",
        "Left half": "Metà sinistra",
        "Right half": "Metà destra",
        "Top half": "Metà superiore",
        "Bottom half": "Metà inferiore",
        "Top left quarter": "Quarto superiore sinistro",
        "Bottom left quarter": "Quarto inferiore sinistro",
        "Top right quarter": "Quarto superiore destro",
        "Bottom right quarter": "Quarto inferiore destro",
        "Top left eighth": "Ottavo superiore sinistro",
        "Bottom left eighth": "Ottavo inferiore sinistro",
        "Top right eighth": "Ottavo superiore destro",
        "Bottom right eighth": "Ottavo inferiore destro",
    ],

    // MARK: Portuguese
    .portuguese: [
        "Settings...": "Configurações...",
        "Quit": "Sair",
        "Language": "Idioma",
        "Modifier Key": "Tecla modificadora",
        "Window Sizes": "Tamanhos de janela",
        "Preview": "Prévia",
        "Permissions": "Permissões",
        "Window Switcher": "Alternador de janelas",
        "Window Control": "Controle de janelas",
        "Move to Desktop": "Mover para área de trabalho",
        "Hotkeys": "Atalhos",
        "Left width:": "Largura esquerda:",
        "Left: %d%% / Right: %d%%": "Esquerda: %d%% / Direita: %d%%",
        "Top height:": "Altura superior:",
        "Top: %d%% / Bottom: %d%%": "Cima: %d%% / Baixo: %d%%",
        "Accessibility": "Acessibilidade",
        "Grant": "Permitir",
        "OK": "OK",
        "Refresh Status": "Atualizar status",
        "Launch at Login": "Iniciar no login",
        "Enable %@ + Tab window switcher": "Ativar alternador %@ + Tab",
        "Experimental feature. Works best within a single Space — switching to windows on other Spaces may be unreliable.": "Recurso experimental. Funciona melhor em um único Space — alternar para outros Spaces pode ser instável.",
        "Enable window control hotkeys": "Ativar atalhos de controle",
        "Maximize / Restore": "Maximizar / Restaurar",
        "Minimize all windows": "Minimizar todas as janelas",
        "Minimize active window": "Minimizar janela ativa",
        "Close active window": "Fechar janela ativa",
        "Center window": "Centralizar janela",
        "Enable %@ + 1–9 to move window": "Ativar %@ + 1–9 para mover",
        "Switch windows (experimental)": "Alternar janelas (experimental)",
        "Center (%d%%)": "Centralizar (%d%%)",
        "Move window to Desktop N": "Mover janela para área de trabalho N",
        "Left half": "Metade esquerda",
        "Right half": "Metade direita",
        "Top half": "Metade superior",
        "Bottom half": "Metade inferior",
        "Top left quarter": "Quarto superior esquerdo",
        "Bottom left quarter": "Quarto inferior esquerdo",
        "Top right quarter": "Quarto superior direito",
        "Bottom right quarter": "Quarto inferior direito",
        "Top left eighth": "Oitavo superior esquerdo",
        "Bottom left eighth": "Oitavo inferior esquerdo",
        "Top right eighth": "Oitavo superior direito",
        "Bottom right eighth": "Oitavo inferior direito",
    ],

    // MARK: Polish
    .polish: [
        "Settings...": "Ustawienia...",
        "Quit": "Zakończ",
        "Language": "Język",
        "Modifier Key": "Klawisz modyfikujący",
        "Window Sizes": "Rozmiary okien",
        "Preview": "Podgląd",
        "Permissions": "Uprawnienia",
        "Window Switcher": "Przełącznik okien",
        "Window Control": "Sterowanie oknami",
        "Move to Desktop": "Przenieś na pulpit",
        "Hotkeys": "Skróty klawiszowe",
        "Left width:": "Szerokość lewa:",
        "Left: %d%% / Right: %d%%": "Lewo: %d%% / Prawo: %d%%",
        "Top height:": "Wysokość górna:",
        "Top: %d%% / Bottom: %d%%": "Góra: %d%% / Dół: %d%%",
        "Accessibility": "Dostępność",
        "Grant": "Zezwól",
        "OK": "OK",
        "Refresh Status": "Odśwież status",
        "Launch at Login": "Uruchamiaj przy logowaniu",
        "Enable %@ + Tab window switcher": "Włącz przełącznik %@ + Tab",
        "Experimental feature. Works best within a single Space — switching to windows on other Spaces may be unreliable.": "Funkcja eksperymentalna. Działa najlepiej w jednym Space — przełączanie do innych Space może być zawodne.",
        "Enable window control hotkeys": "Włącz skróty sterowania oknami",
        "Maximize / Restore": "Maksymalizuj / Przywróć",
        "Minimize all windows": "Minimalizuj wszystkie okna",
        "Minimize active window": "Minimalizuj aktywne okno",
        "Close active window": "Zamknij aktywne okno",
        "Center window": "Wyśrodkuj okno",
        "Enable %@ + 1–9 to move window": "Włącz %@ + 1–9 do przenoszenia",
        "Switch windows (experimental)": "Przełącz okna (eksperymentalnie)",
        "Center (%d%%)": "Wyśrodkuj (%d%%)",
        "Move window to Desktop N": "Przenieś okno na pulpit N",
        "Left half": "Lewa połowa",
        "Right half": "Prawa połowa",
        "Top half": "Górna połowa",
        "Bottom half": "Dolna połowa",
        "Top left quarter": "Górna lewa ćwierć",
        "Bottom left quarter": "Dolna lewa ćwierć",
        "Top right quarter": "Górna prawa ćwierć",
        "Bottom right quarter": "Dolna prawa ćwierć",
        "Top left eighth": "Górna lewa ósma",
        "Bottom left eighth": "Dolna lewa ósma",
        "Top right eighth": "Górna prawa ósma",
        "Bottom right eighth": "Dolna prawa ósma",
    ],

    // MARK: Chinese Simplified
    .chinese: [
        "Settings...": "设置...",
        "Quit": "退出",
        "Language": "语言",
        "Modifier Key": "修饰键",
        "Window Sizes": "窗口尺寸",
        "Preview": "预览",
        "Permissions": "权限",
        "Window Switcher": "窗口切换器",
        "Window Control": "窗口控制",
        "Move to Desktop": "移动到桌面",
        "Hotkeys": "快捷键",
        "Left width:": "左侧宽度：",
        "Left: %d%% / Right: %d%%": "左：%d%% / 右：%d%%",
        "Top height:": "顶部高度：",
        "Top: %d%% / Bottom: %d%%": "上：%d%% / 下：%d%%",
        "Accessibility": "辅助功能",
        "Grant": "授权",
        "OK": "好",
        "Refresh Status": "刷新状态",
        "Launch at Login": "登录时启动",
        "Enable %@ + Tab window switcher": "启用 %@ + Tab 窗口切换器",
        "Experimental feature. Works best within a single Space — switching to windows on other Spaces may be unreliable.": "实验性功能。在单个 Space 中效果最佳——切换到其他 Space 的窗口可能不稳定。",
        "Enable window control hotkeys": "启用窗口控制快捷键",
        "Maximize / Restore": "最大化 / 还原",
        "Minimize all windows": "最小化所有窗口",
        "Minimize active window": "最小化活动窗口",
        "Close active window": "关闭活动窗口",
        "Center window": "居中窗口",
        "Enable %@ + 1–9 to move window": "启用 %@ + 1–9 移动窗口",
        "Switch windows (experimental)": "切换窗口（实验性）",
        "Center (%d%%)": "居中 (%d%%)",
        "Move window to Desktop N": "将窗口移至桌面 N",
        "Left half": "左半部分",
        "Right half": "右半部分",
        "Top half": "上半部分",
        "Bottom half": "下半部分",
        "Top left quarter": "左上四分之一",
        "Bottom left quarter": "左下四分之一",
        "Top right quarter": "右上四分之一",
        "Bottom right quarter": "右下四分之一",
        "Top left eighth": "左上八分之一",
        "Bottom left eighth": "左下八分之一",
        "Top right eighth": "右上八分之一",
        "Bottom right eighth": "右下八分之一",
    ],

    // MARK: Japanese
    .japanese: [
        "Settings...": "設定...",
        "Quit": "終了",
        "Language": "言語",
        "Modifier Key": "修飾キー",
        "Window Sizes": "ウィンドウサイズ",
        "Preview": "プレビュー",
        "Permissions": "権限",
        "Window Switcher": "ウィンドウスイッチャー",
        "Window Control": "ウィンドウ操作",
        "Move to Desktop": "デスクトップに移動",
        "Hotkeys": "ショートカット",
        "Left width:": "左の幅：",
        "Left: %d%% / Right: %d%%": "左：%d%% / 右：%d%%",
        "Top height:": "上の高さ：",
        "Top: %d%% / Bottom: %d%%": "上：%d%% / 下：%d%%",
        "Accessibility": "アクセシビリティ",
        "Grant": "許可",
        "OK": "OK",
        "Refresh Status": "状態を更新",
        "Launch at Login": "ログイン時に起動",
        "Enable %@ + Tab window switcher": "%@ + Tab スイッチャーを有効化",
        "Experimental feature. Works best within a single Space — switching to windows on other Spaces may be unreliable.": "実験的機能。単一Spaceで最もよく機能します—他のSpaceのウィンドウへの切り替えが不安定な場合があります。",
        "Enable window control hotkeys": "ウィンドウ操作ショートカットを有効化",
        "Maximize / Restore": "最大化 / 元に戻す",
        "Minimize all windows": "すべてのウィンドウを最小化",
        "Minimize active window": "アクティブウィンドウを最小化",
        "Close active window": "アクティブウィンドウを閉じる",
        "Center window": "ウィンドウを中央に",
        "Enable %@ + 1–9 to move window": "%@ + 1–9 で移動を有効化",
        "Switch windows (experimental)": "ウィンドウ切替（実験的）",
        "Center (%d%%)": "中央 (%d%%)",
        "Move window to Desktop N": "ウィンドウをデスクトップNに移動",
        "Left half": "左半分",
        "Right half": "右半分",
        "Top half": "上半分",
        "Bottom half": "下半分",
        "Top left quarter": "左上1/4",
        "Bottom left quarter": "左下1/4",
        "Top right quarter": "右上1/4",
        "Bottom right quarter": "右下1/4",
        "Top left eighth": "左上1/8",
        "Bottom left eighth": "左下1/8",
        "Top right eighth": "右上1/8",
        "Bottom right eighth": "右下1/8",
    ],

    // MARK: Hindi
    .hindi: [
        "Settings...": "सेटिंग्स...",
        "Quit": "बंद करें",
        "Language": "भाषा",
        "Modifier Key": "मॉडिफायर कुंजी",
        "Window Sizes": "विंडो आकार",
        "Preview": "पूर्वावलोकन",
        "Permissions": "अनुमतियाँ",
        "Window Switcher": "विंडो स्विचर",
        "Window Control": "विंडो नियंत्रण",
        "Move to Desktop": "डेस्कटॉप पर ले जाएं",
        "Hotkeys": "शॉर्टकट कुंजियाँ",
        "Left width:": "बाईं चौड़ाई:",
        "Left: %d%% / Right: %d%%": "बाएं: %d%% / दाएं: %d%%",
        "Top height:": "ऊपरी ऊंचाई:",
        "Top: %d%% / Bottom: %d%%": "ऊपर: %d%% / नीचे: %d%%",
        "Accessibility": "सहायकता",
        "Grant": "अनुमति दें",
        "OK": "ठीक है",
        "Refresh Status": "स्थिति रीफ्रेश करें",
        "Launch at Login": "लॉगिन पर लॉन्च करें",
        "Enable %@ + Tab window switcher": "%@ + Tab विंडो स्विचर सक्षम करें",
        "Experimental feature. Works best within a single Space — switching to windows on other Spaces may be unreliable.": "प्रयोगात्मक सुविधा। एकल Space में सबसे अच्छा काम करता है — अन्य Space की विंडो पर स्विच करना अस्थिर हो सकता है।",
        "Enable window control hotkeys": "विंडो नियंत्रण शॉर्टकट सक्षम करें",
        "Maximize / Restore": "अधिकतम करें / पुनर्स्थापित करें",
        "Minimize all windows": "सभी विंडो छोटी करें",
        "Minimize active window": "सक्रिय विंडो छोटी करें",
        "Close active window": "सक्रिय विंडो बंद करें",
        "Center window": "विंडो केंद्र में करें",
        "Enable %@ + 1–9 to move window": "%@ + 1–9 से विंडो ले जाना सक्षम करें",
        "Switch windows (experimental)": "विंडो स्विच करें (प्रयोगात्मक)",
        "Center (%d%%)": "केंद्र (%d%%)",
        "Move window to Desktop N": "विंडो को डेस्कटॉप N पर ले जाएं",
        "Left half": "बाईं आधी",
        "Right half": "दाईं आधी",
        "Top half": "ऊपरी आधी",
        "Bottom half": "निचली आधी",
        "Top left quarter": "ऊपरी बाईं चौथाई",
        "Bottom left quarter": "निचली बाईं चौथाई",
        "Top right quarter": "ऊपरी दाईं चौथाई",
        "Bottom right quarter": "निचली दाईं चौथाई",
        "Top left eighth": "ऊपरी बाईं आठवीं",
        "Bottom left eighth": "निचली बाईं आठवीं",
        "Top right eighth": "ऊपरी दाईं आठवीं",
        "Bottom right eighth": "निचली दाईं आठवीं",
    ],
]
